version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/clean
hooks:
    BeforeInstall:
      - location: scripts/install_dependancies
        timeout: 300
        runas: root
    ApplicationStop:
      - location: scripts/stop_server
        timeout: 300
        runas: root
    ApplicationStart:
      - location: scripts/start_server
        timeoout: 300
        runas: root
